name: CI
on: [push]
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_11.3.app
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug build
